export  const APP_FEATURES = [
    {
        id:"01",
        title:"Learn at Your Own Pace",
        description:"Expand answers when you are ready . Dive deeper into any concept instanly with AI-Powered detailed infromation"

    },
     {
        id:"02",
        title:"Tailored Just For You",
        description:"Get interview questions and model answers based on your role , experience and secific focus areas"

    },
     {
        id:"03",
        title:"Capture Your Insights",
        description:"Add personal notes to any question and pin important ones to the top - making your learing more organized"

    },
     {
        id:"04",
        title:"Understand the 'Why' behind the answers",
        description:" Beyond Just answers - unlock detailed  concept of explantions generated by AI , helping you truly master each and every concept"

    },
     {
        id:"05",
        title:"Save , Organize and Revisit",
        description:"Easily save your interview sets , organize them nearly in your dashboard and pick your right file to fasten your learning "

    },

]