export const CARD_BG = [
    {id : 1 ,bgcolor:'linear-gradient(135deg , #e6f8f3 0% , #f7fcfa 100% )'},
     {id : 2 ,bgcolor:'linear-gradient(135deg , #fef9e7 0% , #fffdf4 100% )'},
      {id : 3 ,bgcolor:'linear-gradient(135deg , #eaf7ff 0% , #f3fbff 100% )'},
       {id : 4 ,bgcolor:'linear-gradient(135deg , #fff2e9 0% , #fff8f3 100% )'},
        {id : 5 ,bgcolor:'linear-gradient(135deg , #e7f6fe 0% , #f4fafd 100% )'},
         {id : 6 ,bgcolor:'linear-gradient(135deg , #f5f5f5 0% , #fbfbfb 100% )'},
          {id : 7 ,bgcolor:'linear-gradient(135deg , #fff4fc 0% , #fff8fd 100% )'},
           {id : 8 ,bgcolor:'linear-gradient(135deg , #e8fef3 0% , #f5fef8 100% )'},
            {id : 9 ,bgcolor:'linear-gradient(135deg , #f0ecff 0% , #f7f5ff 100% )'},
             {id : 10 ,bgcolor:'linear-gradient(135deg , #fef2f2 0% , #fff8f8 100% )'},

]




export  const APP_FEATURES = [
    {
        id:"01",
        title:"Learn at Your Own Pace",
        description:"Expand answers when you are ready . Dive deeper into any concept instanly with AI-Powered detailed infromation"

    },
     {
        id:"02",
        title:"Tailored Just For You",
        description:"Get interview questions and model answers based on your role , experience and secific focus areas"

    },
     {
        id:"03",
        title:"Capture Your Insights",
        description:"Add personal notes to any question and pin important ones to the top - making your learing more organized"

    },
     {
        id:"04",
        title:"Understand the 'Why' behind the answers",
        description:" Beyond Just answers - unlock detailed  concept of explantions generated by AI , helping you truly master each and every concept"

    },
     {
        id:"05",
        title:"Save , Organize and Revisit",
        description:"Easily save your interview sets , organize them nearly in your dashboard and pick your right file to fasten your learning "

    },

]